cliente/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    # Página inicial
    url(r'^$', views.index, name='index'),
    url(r'^clientes/$', views.clientes, name = 'clientes'),
    url(r'clientes/(?P<cliente_id>\d+)/$', views.cliente, name='cliente'),
    url(r'clientes-api/$', views.ClienteLista.as_view(), name='clientes-api'),
    url(r'clientes-api/(?P<cliente_id>\d+)/$', views.ClienteDetalhe.as_view(), name='cliente-api'),
    url(r'clientes-api/pesquisar/$', views.ClienteFiltro.as_view(), name='cliente-filtro'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

webservice/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings                # import to work with static files
from django.conf.urls.static import static      # import to work with static files

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('cliente.urls', namespace='cliente')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # +... added to work with static files

cliente/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14)
    opcoes = (('0', 'Masculino'),('1', 'Feminino'))
    sexo = models.CharField(max_length=10, choices=opcoes)
    idade = models.IntegerField(
        validators=[MaxValueValidator(130),
                    MinValueValidator(0)
                ]
        )
    data_adc = models.DateField(auto_now_add=True)
    data_upd = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return (self.nome + " " + self.sobrenome)

cliente/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import ClienteSerializer
from .models import Cliente

# Create your views here.
def index(request):
    """A página inicial de Clientes"""
    return render(request, 'cliente/index.html')

def clientes(request):
    clts = Cliente.objects.all()
    context = {
        'clientes' : clts,
    }
    lista = []
    for i in clts:
        cliente = {'nome' : i.nome + ' ' + i.sobrenome,'cpf' : i.cpf, 'idade' : i.idade, 'sexo' : i.sexo}
        lista.append(cliente)
    print(lista)

    return render(request, 'cliente/clientes.html', context)

def cliente(request, cliente_id):
    cliente = Cliente.objects.get(id=cliente_id)
    context = {
        'cliente' : cliente,
    }
    return render(request, 'cliente/cliente.html', context)



class ClienteLista(APIView):

    def get(self, request):
        clientes = Cliente.objects.all()
        serializer = ClienteSerializer(clientes, many=True)
        return Response(serializer.data)

    def post(self,request):
        serializer = ClienteSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ClienteFiltro(APIView):

    def post(self, request):
        pesquisa = request.data
        termo = pesquisa['pesquisa']
        clientes = Cliente.objects.all().filter(
            Q(nome__icontains=termo) |
            Q(sobrenome__icontains=termo) |
            Q(cpf__icontains=termo) |
            Q(idade__icontains=termo)
        )

        serializer = ClienteSerializer(clientes, many=True)
        return Response(serializer.data)


class ClienteDetalhe(APIView):

    def get(self, request, cliente_id):
        cliente = Cliente.objects.get(pk=cliente_id)
        serializer = ClienteSerializer(cliente)
        return Response(serializer.data)

    def post(self,request, cliente_id):
        cliente = Cliente.objects.get(pk=cliente_id)
        serializer = ClienteSerializer(data=request.data)
        if serializer.is_valid():
            # serializer.save()
            r = request.POST
            cliente.nome = r['nome']
            cliente.sobrenome = r['sobrenome']
            cliente.cpf = r['cpf']
            cliente.idade = r['idade']
            cliente.sexo = r['sexo']
            cliente.save()

            return Response(serializer.data, status=status.HTTP_201_CREATED)

    def delete (self,request, cliente_id):
        serializer = Cliente.objects.get(pk=cliente_id)
        serializer.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

cliente/templates/cliente/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Webservice - GUI</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'cliente/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'cliente/css/estilo.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">

      <button type="button" class="navbar-toggler" data-toggle="collapse"
      data-target="#navbarSite">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSite">
        <div class="container">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a href="{% url 'cliente:index' %}" class="nav-link">Inicio</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'cliente:clientes' %}" class="nav-link">Clientes</a>
            </li>
          </ul>
          </div>
      </div>

    </nav>
    {% block content %}
    {% endblock %}

    <!-- FOOTER -->
    <hr class="mt-5">
    <footer class="container">
      <div class="row">
        <div class="col-6">
          <p class="float-right pr-0"></p>
          <p>Copyright 2018. &copy; Webservice. Todos os direitos reservados.
        </div>
        <div class="col-6 pl-0">
          Desenvolvido por
          <a href="#">
            Guilherme Luis
          </a> &middot;
        </div>
        </p>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

cliente/templates/cliente/cliente.html
{% extends "cliente/base.html" %}
{% load staticfiles %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Cliente {{ cliente.nome }}</h1>
  </div>
</div>

<div class="container">
  <div class="container">
    <h4>Nome: {{ cliente.nome }} {{ cliente.sobrenome }}</h4>
    <h4>Sexo: {{ cliente.sexo }}</h4>
    <h4>CPF: {{ cliente.cpf }}</h4>
    <h4>Idade: {{ cliente.idade }}</h4>
    <h4>API: <a href="{% url 'cliente:cliente-api' cliente.id %}">link</a></h4>
    
  </div>
</div>

{% endblock %}

cliente/templates/cliente/clientes.html
{% extends "cliente/base.html" %}
{% load staticfiles %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Clientes</h1>
    <h4>API: <a href="{% url 'cliente:clientes-api' %}">link</a></h4>
  </div>
</div>

<div class="container">
  <table class="table table-hover">
    <thead class="thead-dark initialism" align="center">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Sexo</th>
        <th scope="col">Idade</th>
      </tr>
    </thead>
    <tbody align="center">
      {% for i in clientes %}
      <tr>
        <td>
          <a href="{% url 'cliente:cliente' i.id %}">{{i.nome}}</a>

        </td>
        <td>{{i.sexo}}</td>
        <td>{{i.idade}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

cliente/templates/cliente/index.html
{% extends "cliente/base.html" %}
{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Olá, Mundo!</h1>
  </div>
</div>

{% endblock %}